# Generated by Django 5.0.3 on 2024-03-06 18:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(6)])),
            ],
        ),
        migrations.CreateModel(
            name='IHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('category', models.CharField(choices=[('OPTION1', 'IHA 0'), ('OPTION2', 'IHA 1'), ('OPTION3', 'IHA 2'), ('OPTION4', 'IHA 4')], max_length=50)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('total_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.customers')),
                ('iha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.iha')),
            ],
        ),
    ]
