# Generated by Django 5.0.3 on 2024-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
