# Generated by Django 5.0.3 on 2024-03-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_alter_customers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='finish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
