# Generated by Django 5.0.3 on 2024-03-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0003_alter_reservations_finish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
