# Generated by Django 5.0.3 on 2024-03-07 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0004_reservations_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='iha',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='iha_images/'),
        ),
        migrations.AlterField(
            model_name='iha',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='iha',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
